### PR TITLE
Support for Carthage

### PR DESCRIPTION
**Pull request by tsuharesu**
I changed the project so it is a Framework instead of an App. 
I also put it in a Workspace and bumped the version.

### CODE REVIEW

**Comment by weekwood** [comment]
Thanks @tsuharesu! 
Everything looks good.  and fix my typo too. Can you change project name from _.travis.yml_ and make test working from xctool. 
Very excited to get your PR.

**Comment by weekwood** [comment]
look like you need remove library from
image

**Comment by tsuharesu** [comment]
Yeah, I didn't saw travis.yml... Will work it out today.

**Comment by tsuharesu** [comment]
Yey, passing!

**Comment by weekwood** [comment]
Good job @tsuharesu

**Pull request merged**
